sudo: required
services:
  - docker

before-install:
  - docker build -t peatonet/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true peatonet/docker-react npm run test
  
language: generic 
